---
- name: Copy CS:GO server script
  copy:
    src: run-csgo.sh
    dest: /home/steam/run-csgo.sh
    owner: steam
    group: steam
    mode: ugo=rx

- name: Copy tournament configs
  copy:
    force: no
    src: confs/
    dest: /home/steam/csgo/csgo/cfg/
    owner: steam
    group: steam

- include: ebot.yml

- include: get5.yml

- name: Generate autoexec.cfg
  template:
    src: autoexec.cfg
    dest: '/home/steam/csgo/csgo/cfg/autoexec.cfg'
    owner: steam
    group: steam

- name: Copy CS:GO logging config
  template:
    src: logging.cfg
    dest: '/home/steam/csgo/csgo/cfg/logging.cfg'
    owner: steam
    group: steam

- name: Copy CS:GO GOTV config
  template:
    src: gotv.cfg
    dest: '/home/steam/csgo/csgo/cfg/gotv.cfg'
    owner: steam
    group: steam

- include: instance.yml
