---
- name: Docker build directory
  tempfile:
    state: directory
  register: get5_docker

- name: Copy get5 web config to server
  template:
    src: prod_config.py
    dest: '{{ get5_docker.path }}/prod_config.py'
    owner: root
    group: root
    mode: 0644

- name: Copy get5 web entry to server
  copy:
    src: '{{ item }}'
    dest: '{{ get5_docker.path }}/{{ item }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - 'entry.sh'
    - 'dockerfile'

- name: Build get5 web docker image
  docker_image:
    build:
      dockerfile: dockerfile
      path: '{{ get5_docker.path }}'
    state: present
    name: get5-web
    force: yes

- name: get5 web database schema
  become: yes
  shell:
    cmd: "docker run --network csgo-manager --rm get5-web python manager.py db upgrade"

- name: Download system2
  get_url:
    url: "https://github.com/dordnung/System2/releases/download/v3.2.1/system2.zip"
    dest: "/home/steam/system2.zip"

- name: Unpack system2
  unarchive:
    src: "/home/steam/system2.zip"
    dest: "/home/steam/csgo/csgo/addons/sourcemod/"
    remote_src: yes

- name: Fix system2 permissions
  file:
    path: "/home/steam/csgo/csgo/addons/sourcemod/{{item}}"
    mode: a+rx
  with_items:
    - "extensions/system2.ext.so"
    - "scripting/system2_http.sp"
    - "scripting/system2_test.sp"
    - "scripting/include/system2.inc"
    - "scripting/include/system2/legacy.inc"
    - "scripting/include/system2/request.inc"

- name: get5 web interface container
  docker_container:
    image: get5-web
    name: get5-web
    purge_networks: yes
    networks:
      - name: csgo-manager
    published_ports: '0.0.0.0:5000:5000'
    restart_policy: unless-stopped
