---
- name: Counter-Strike Global Offensive server
  hosts: csgo
  become: yes
  tasks:
    - include_role:
        name: steamcmd
    - include_role:
        name: cs-go
      vars:
        instances:
          - name: '1'
            gslt: '3A3B0E2FC463309618A1942B356316C5'
            rcon_password: 'password'
  tags:
    - csgo

- name: eBot
  hosts: ebot
  become: yes
  tasks:
    - include_role:
        name: docker
    - include_role:
        name: ebot
      vars:
        mysql_password: 'test'
        mysql_root_password: 'test'
        ebot_admin_user: 'admin'
        ebot_admin_password: 'password'
        ebot_admin_email: 'ebot@example.com'
        external_ip: '192.168.122.195'
  tags:
    - ebot
