---
- name: Install python
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: install python3 for ansible
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
  tags:
    - setup

#- name: Misc
#  hosts: all
#  become: yes
#  tasks:
#    - include_role:
#        name: sudo
#    - include_role:
#        name: users
#  vars_files:
#    - vars/users.yml
#    - vars/misc.yml
#  tags:
#    - misc

- name: Install Counter-Strike Global Offensive
  hosts:
    - csgo
    - csgo-relay
  become: yes
  tasks:
    - include_vars:
        file: vars/logging.yml
        name: logging
    - include_vars:
        file: vars/csgo-instances.yml
        name: csgo
    - include_vars:
        file: vars/misc.yml
    - fail:
        msg: "Server doesn't have a instance configuration"
      when: 'ansible_facts.nodename not in csgo["servers"] and ansible_facts.nodename not in csgo["relays"]'
    - include_role:
        name: steamcmd
      vars:
        steamcache: false
    - include_role:
        name: csgo/common

- name: Counter-Strike Global Offensive server
  hosts: csgo
  become: yes
  tasks:
    - include_vars:
        file: vars/logging.yml
        name: logging
    - include_vars:
        file: vars/csgo-instances.yml
        name: csgo
    - include_vars:
        file: vars/misc.yml
    - include_vars:
        file: vars/get5.yml
        name: get5
    - include_role:
        name: csgo/game
    - include_role:
        name: demo-uploader
  tags:
    - csgo

- name: Manager
  hosts: manager
  become: yes
  tasks:
    - include_vars:
        file: vars/misc.yml
    - include_vars:
        file: vars/get5.yml
        name: get5
    - include_role:
        name: docker
    - include_role:
        name: database
    - include_role:
        name: ebot
      vars:
        external_ip: '{{ ansible_facts[ips[ansible_facts.nodename].interface].ipv4.address }}'
    - include_role:
        name: get5
  vars_files:
    - vars/ebot.yml
    - vars/ips.yml
    - vars/misc.yml
  tags:
    - manager

- name: CS:GO GOTV relay
  hosts: csgo-relay
  become: yes
  tasks:
    - include_vars:
        file: vars/csgo-instances.yml
        name: csgo
    - include_vars:
        file: vars/misc.yml
    - fail:
        msg: "Server doesn't have a instance configuration"
      when: 'ansible_facts.nodename not in csgo["relays"]'
    - include_role:
        name: steamcmd
      vars:
        steamcache: false
    - include_role:
        name: csgo/common
    - include_role:
        name: csgo/relay
