---
- name: Install python
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: install python2 for ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  tags:
    - setup

- name: Misc
  hosts: all
  become: yes
  tasks:
    - include_role:
        name: sudo
    - include_role:
        name: users
  vars_files:
    - vars/users.yml
    - vars/misc.yml
  tags:
    - misc

- name: Counter-Strike Global Offensive server
  hosts: csgo
  become: yes
  tasks:
    - include_role:
        name: steamcmd
      vars:
        steamcache: yes
    - include_role:
        name: csgo
  vars_files:
    - vars/csgo-instances.yml
    - vars/misc.yml
  tags:
    - csgo

- name: Manager
  hosts: manager
  become: yes
  tasks:
    - include_role:
        name: docker
    - include_role:
        name: database
    - include_role:
        name: ebot
      vars:
        external_ip: '{{ ansible_facts[ips[ansible_facts.nodename].interface].ipv4.address }}'
    - include_role:
        name: get5
  vars_files:
    - vars/ebot.yml
    - vars/ips.yml
    - vars/misc.yml
  tags:
    - manager
