---
- name: Check if CS:GO is installed
  stat:
    path: /home/steam/csgo/csgo
  register: csgostat

- name: Install CS:GO server
  script: install-csgo.sh
  when: csgostat.stat.exists == False
  # Note: if app_update failed with state 0x202 it's probably due to not enough available disk space

- name: Update CS:GO server
  script: update-csgo.sh
  when: csgostat.stat.exists == True

- name: Copy tournament configs
  copy:
    force: no
    src: confs/
    dest: /home/steam/csgo/csgo/cfg/
    owner: steam
    group: steam

- include: ebot.yml

- include: get5.yml

- name: Generate autoexec.cfg
  template:
    src: autoexec.cfg
    dest: '/home/steam/csgo/csgo/cfg/autoexec.cfg'
    owner: steam
    group: steam
