---
- name: Install CS:GO dependencies
  apt:
    name: '{{ item }}'
    state: present
  loop:
    - 'libcurl3'

- name: Check if CS:GO is installed
  stat:
    path: /home/steam/csgo/csgo
  register: csgostat

- name: Install CS:GO server
  script: install-csgo.sh
  when: csgostat.stat.exists == False
  become: yes
  become_user: steam
  # Note: if app_update failed with state 0x202 it's probably due to not enough available disk space

- name: Update CS:GO server
  script: update-csgo.sh
  when: csgostat.stat.exists == True
  become: yes
  become_user: steam
