---
- name: Enable i386 architecture in dpkg
  shell: 'dpkg --add-architecture i386'

- name: Update package repository
  apt:
    update_cache: yes

- name: Install CS:GO dependencies
  apt:
    name: '{{ item }}'
    state: present
  loop:
    - 'libcurl3:i386'

- name: Check if CS:GO is installed
  stat:
    path: /home/steam/csgo/csgo
  register: csgostat

- name: Install CS:GO server
  script: install-csgo.sh
  when: csgostat.stat.exists == False
  become: yes
  become_user: steam
  # Note: if app_update failed with state 0x202 it's probably due to not enough available disk space

- name: Update CS:GO server
  script: update-csgo.sh
  when: csgostat.stat.exists == True
  become: yes
  become_user: steam

- name: Link libcurl.so
  file:
    state: link
    src: "/usr/lib/i386-linux-gnu/libcurl.so.4"
    dest: "/home/steam/csgo/bin/libcurl.so"
    mode: u=rwx,go=rx
    owner: steam
    group: steam
