---
- name: Copy CS:GO systemd service to server
  copy:
    src: csgo@.service
    dest: /etc/systemd/system/csgo@.service
    owner: root
    group: root
    mode: u=rw,go=r

- name: Reload systemd
  systemd:
    daemon_reload: yes
