---
- name: eBot database (mysql) cotainer
  docker_container:
    name: ebot-mysql
    image: mysql:5
    networks:
      - name: ebot
        aliases:
          - database
    env:
      MYSQL_ROOT_PASSWORD: '{{mysql_root_password}}'
    purge_networks: yes
  register: mysql

#- name: Install MySQL
#  apt:
#    state: present
#    name: mysql-server

#- name: MySQL service
#  systemd:
#    name: mysql.service
#    state: started
#    enabled: yes

- name: Ansible mysql library
  apt:
    state: latest
    name: python-pymysql

- name: eBot MySQL database
  mysql_db:
    name: ebot
    state: present
    login_host: '{{mysql.ansible_facts.docker_container.NetworkSettings.Networks.ebot.IPAddress}}'
    login_password: '{{mysql_root_password}}'
    login_user: 'root'
    #login_unix_socket: /var/run/mysqld/mysqld.sock

- name: eBot MySQL user
  mysql_user:
    name: ebot
    password: '{{mysql_password}}'
    host: '%'
    priv: 'ebot.*:ALL'
    login_host: '{{mysql.ansible_facts.docker_container.NetworkSettings.Networks.ebot.IPAddress}}'
    login_password: '{{mysql_root_password}}'
    login_user: 'root'
    #check_implicit_admin: yes
    #login_unix_socket: /var/run/mysqld/mysqld.sock
