---
- name: eBot container
  docker_container:
    name: ebot
    image: kaganus/ebot
    purge_networks: yes
    networks:
      - name: ebot
        aliases:
          - ebot
    published_ports:
      - '0.0.0.0:12360:12360/tcp'
      - '0.0.0.0:12360:12360/udp'
      - '0.0.0.0:12361:12361/tcp'
      - '0.0.0.0:12361:12361/udp'
    env:
      EXTERNAL_IP: '{{external_ip}}'
      MYSQL_HOST: 'database'
      MYSQL_PORT: '3306'
      MYSQL_DB: 'ebot'
      MYSQL_USER: 'ebot'
      MYSQL_PASS: '{{mysql_password}}'
      LO3_METHOD: 'restart'
      KO3_METHOD: 'restart'
      DEMO_DOWNLOAD: 'true'
      REMIND_RECORD: 'false'
      DAMAGE_REPORT: 'true'
      DELAY_READY: 'false'
      NODE_STARTUP_METHOD: 'node'
      USE_DELAY_END_RECORD: 'true'
    restart_policy: always

- name: eBot web interface container
  docker_container:
    name: ebot-web
    image: kaganus/ebotweb
    purge_networks: yes
    networks:
      - name: ebot
    published_ports: '0.0.0.0:8080:80'
    env:
      EBOT_IP: '{{external_ip}}'
      EBOT_PORT: 12360
      EBOT_ADMIN_USER: '{{ebot_admin_user}}'
      EBOT_ADMIN_PASS: '{{ebot_admin_password}}'
      EBOT_ADMIN_MAIL: '{{ebot_admin_email}}'
      MYSQL_HOST: 'database'
      MYSQL_PORT: '3306'
      MYSQL_DB: 'ebot'
      MYSQL_USER: 'ebot'
      MYSQL_PASS: '{{mysql_password}}'
      DEMO_DOWNLOAD: 'true'
      DEFAULT_RULES: 'esl5on5'
    restart_policy: always
