---
- name: Database (mysql) cotainer
  docker_container:
    name: csgo-mysql
    image: mysql:5
    purge_networks: yes
    networks:
      - name: csgo-manager
        aliases:
          - database
    env:
      MYSQL_ROOT_PASSWORD: '{{mysql_root_password}}'
    restart_policy: always
  register: mysql

- name: Ansible mysql library (python3)
  apt:
    state: latest
    name: python3-pymysql

- name: Ansible mysql library (python2)
  apt:
    state: latest
    name: python-pymysql

- name: Wait for MySQL to start
  wait_for:
    host: '{{mysql.ansible_facts.docker_container.NetworkSettings.Networks["csgo-manager"].IPAddress}}'
    port: 3306

- name: eBot MySQL database
  mysql_db:
    name: ebot
    state: present
    login_host: '{{mysql.ansible_facts.docker_container.NetworkSettings.Networks["csgo-manager"].IPAddress}}'
    login_password: '{{mysql_root_password}}'
    login_user: 'root'

- name: eBot MySQL user
  mysql_user:
    name: ebot
    password: '{{mysql_password}}'
    host: '%'
    priv: 'ebot.*:ALL'
    login_host: '{{mysql.ansible_facts.docker_container.NetworkSettings.Networks["csgo-manager"].IPAddress}}'
    login_password: '{{mysql_root_password}}'
    login_user: 'root'

- name: get5 MySQL database
  mysql_db:
    name: get5
    state: present
    login_host: '{{mysql.ansible_facts.docker_container.NetworkSettings.Networks["csgo-manager"].IPAddress}}'
    login_password: '{{mysql_root_password}}'
    login_user: 'root'

- name: get5 MySQL user
  mysql_user:
    name: get5
    password: '{{ get5.database_password }}'
    host: '%'
    priv: 'get5.*:ALL'
    login_host: '{{mysql.ansible_facts.docker_container.NetworkSettings.Networks["csgo-manager"].IPAddress}}'
    login_password: '{{mysql_root_password}}'
    login_user: 'root'

- name: get5-mysqlstats MySQL database
  mysql_db:
    name: get5stats
    state: present
    login_host: '{{mysql.ansible_facts.docker_container.NetworkSettings.Networks["csgo-manager"].IPAddress}}'
    login_password: '{{mysql_root_password}}'
    login_user: 'root'

- name: get5-mysqlstats MySQL user
  mysql_user:
    name: get5stats
    password: '{{ get5.stats_password }}'
    host: '%'
    priv: 'get5stats.*:ALL'
    login_host: '{{mysql.ansible_facts.docker_container.NetworkSettings.Networks["csgo-manager"].IPAddress}}'
    login_password: '{{mysql_root_password}}'
    login_user: 'root'

- copy:
    src: get5_stats_import.sql
    dest: /home/steam/get5_stats_import.sql
    mode: u=rwx,go=rx
    owner: root
    group: root

- name: get5-mysqlstats schema
  become: yes
  shell:
    cmd: 'docker run --network csgo-manager --rm mysql:5 mysql --host=database --user=root --password="{{ mysql_root_password }}" get5stats < /home/steam/get5_stats_import.sql'
