---
- name: Database (mysql) cotainer
  docker_container:
    name: csgo-mysql
    image: mysql:5
    purge_networks: yes
    networks:
      - name: csgo-manager
        aliases:
          - database
    env:
      MYSQL_ROOT_PASSWORD: '{{mysql_root_password}}'
    restart_policy: always
  register: mysql

- name: Ansible mysql library
  apt:
    state: latest
    name: python-pymysql

- name: Wait for MySQL to start
  wait_for:
    host: '{{mysql.ansible_facts.docker_container.NetworkSettings.Networks["csgo-manager"].IPAddress}}'
    port: 3306

- name: eBot MySQL database
  mysql_db:
    name: ebot
    state: present
    login_host: '{{mysql.ansible_facts.docker_container.NetworkSettings.Networks["csgo-manager"].IPAddress}}'
    login_password: '{{mysql_root_password}}'
    login_user: 'root'

- name: eBot MySQL user
  mysql_user:
    name: ebot
    password: '{{mysql_password}}'
    host: '%'
    priv: 'ebot.*:ALL'
    login_host: '{{mysql.ansible_facts.docker_container.NetworkSettings.Networks["csgo-manager"].IPAddress}}'
    login_password: '{{mysql_root_password}}'
    login_user: 'root'

- name: get5 MySQL database
  mysql_db:
    name: get5
    state: present
    login_host: '{{mysql.ansible_facts.docker_container.NetworkSettings.Networks["csgo-manager"].IPAddress}}'
    login_password: '{{mysql_root_password}}'
    login_user: 'root'

- name: get5 MySQL user
  mysql_user:
    name: get5
    password: '{{mysql_password}}'
    host: '%'
    priv: 'get5.*:ALL'
    login_host: '{{mysql.ansible_facts.docker_container.NetworkSettings.Networks["csgo-manager"].IPAddress}}'
    login_password: '{{mysql_root_password}}'
    login_user: 'root'
