---
- name: Create CS:GO server instance configuration directory
  file:
    path: '/home/steam/conf/csgo/instance/{{ item.name }}'
    state: directory
    owner: steam
    group: steam
  loop: '{{ csgo["relays"][ansible_facts.nodename].instances }}'

- name: Create CS:GO instance config
  template:
    src: service_conf.env
    dest: '/home/steam/conf/csgo/instance/{{ item.name }}/'
    owner: steam
    group: steam
  loop: '{{ csgo["relays"][ansible_facts.nodename].instances }}'

- name: Create CS:GO instance config
  template:
    src: instance.cfg
    dest: '/home/steam/csgo/csgo/cfg/instance_{{ item.name }}.cfg'
    owner: steam
    group: steam
  loop: '{{ csgo["relays"][ansible_facts.nodename].instances }}'

- name: Enable CS:GO server instance
  systemd:
    name: 'csgo@{{ item.name }}.service'
    state: restarted
    enabled: yes
  when: "item.active"
  loop: '{{ csgo["relays"][ansible_facts.nodename].instances }}'

- name: Disable CS:GO server instance
  systemd:
    name: 'csgo@{{ item.name }}.service'
    state: stopped
    enabled: yes
  when: "item.active == false"
  loop: '{{ csgo["relays"][ansible_facts.nodename].instances }}'
