---
- name: Install docker
  apt:
    name: docker.io
    state: latest

- name: Enable dockerd service
  systemd:
    name: docker.service
    state: started
    enabled: yes

- name: Install docker-py for ansible (python3)
  apt:
    name: python3-docker
    state: latest

- name: Install docker-py for ansible (python2)
  apt:
    name: python-docker
    state: latest

- name: CS:GO manager docker network
  docker_network:
    name: csgo-manager
